# Generated by Django 4.2.16 on 2024-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='DewPointAvgF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='DewPointHighF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='DewPointLowF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='HumidityHighPercent',
            field=models.IntegerField(),
        ),
    ]
