# Generated by Django 4.2.16 on 2024-09-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0002_alter_weather_dewpointavgf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='HumidityHighPercent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
