# Generated by Django 4.2.2 on 2024-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Isbn', models.CharField(max_length=13)),
                ('Author', models.TextField()),
                ('Title', models.TextField()),
                ('Category_name', models.TextField(db_column='Category name')),
                ('Category_id', models.IntegerField(db_column='Category id')),
                ('price', models.IntegerField()),
                ('Fixed_price', models.BooleanField(db_column='Fixed price')),
                ('Pub_date', models.DateField(db_column='Pub date')),
            ],
        ),
    ]
